### PR TITLE
Milestone 2: User Interface

### PR DESCRIPTION
**Pull request by diazgio**
## What this PR for :

In this milestone we:

- Add user-interface to main.rb
- Explaining the actions for the users
- Gets information from users

### CODE REVIEW

**Comment by bertil291utn** [comment]
# **Status:** Changes requested 🟠 
<p align="center"> image <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish all the requirements, you required to do these changes, listed below:

* [ ] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid
* [ ] `[REQUIRED]` game displays board after the player move
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move
* [ ] `[REQUIRED]` game repeats all actions for the next player's move

- Remember your game should not finish until the game is over (when there's a winner or it's a draw)
  - [ ] Thus please work with a loop, checking until the game is over
```ruby


# initial instructions for player
# Ask players information
game_ends = if there's a winner or a draw
while !game_ends 
  # loop for each move
  # asking move for each player
  # displaying the board
  # checking if there was a winner/draw
end
```

### Summary

- Guys, remember this part should just display all the steps you will need to play the game, it should not work yet

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Review by bertil291utn — CHANGES_REQUESTED** [review]
# **Status:** Changes requested 🟠 
<p align="center"> image <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish all the requirements, you required to do these changes, listed below:

* [ ] `[REQUIRED]` game asks the player to select from available moves
* [ ] `[REQUIRED]` game informs player if the selected move is invalid
* [ ] `[REQUIRED]` game displays board after the player move
* [ ] `[REQUIRED]` game informs player if the selected move is a winning move
* [ ] `[REQUIRED]` game informs player if the selected move is a draw move
* [ ] `[REQUIRED]` game repeats all actions for the next player's move

- Remember your game should not finish until the game is over (when there's a winner or it's a draw)
  - [ ] Thus please work with a loop, checking until the game is over
```ruby


# initial instructions for player
# Ask players information
game_ends = if there's a winner or a draw
while !game_ends 
  # loop for each move
  # asking move for each player
  # displaying the board
  # checking if there was a winner/draw
end
```

### Summary

- Guys, remember this part should just display all the steps you will need to play the game, it should not work yet

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Comment by krys2fa** [comment]
## Well done @sanadwj and @diazgio  👏 
Your implemented most of the changes requested by my colleague. 💪 

Just a few more adjustments to complete this milestone. They can be seen below:
### Status: Changes Required ♻️ 

- [ ] [REQUIRED] A loop is required in the implementation of this milestone ([OdinProject Hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). 
**HINT:** Implementing the suggestion by the previous TSE should fulfill this requirement.

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Comment by diazgio** [comment]
We add a while loop and inside of this one a loop do, we are working in this way in the next milestone using loops for our methods.

**Comment by krys2fa** [comment]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

**Pull request merged**
